pip install marshal
pip install types
pip install imp
pip install io
pip install ctypes
pip install os
pip install random
pip install string
pip install zlib
pip install base64
pip install dis
pip install ast
pip install sys
pip install zipfile
pip install json
pip install re
pip install subprocess
pip install urllib.request
pip install requests
pip install webbrowser
pip install uuid
pip install pycryptodome
pip install pystyle
pip install colorama
pip install auto_py_to_exe
pip install pyinstaller
pip install wmi
pip install Base64_encode  
pip install AES_encrypt
pip install shutil
pip install getpass
pip install base64
pip install Crypto.Cipher
pip install AES
pip install urllib.request
pip install tempfile